back_media:
    resource: "@BackBundle/Controller/MediaController.php"
    type:     annotation

utilisateurs:
    resource: "@UtilisateursBundle/Controller/"
    type:     annotation
    prefix:   /

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@frontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"