<?php

namespace BackBundle\Repository;

/**
 * ReplayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplayRepository extends \Doctrine\ORM\EntityRepository
{
}
